apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:PRXwIsJAoPadWtJ+CY29W3mmMeynOsLNIsF8ueX4brC89pmc9xBwq3vBWvc6VfoyIroeVYoGHCF34elU4A2L8s3XyJ7WyH+dBc4WiXZIbIXSTwKpdyhubz2zrSAGRVR0V3UcEsRu5+8kwMcZHT6aNHJC3RH8dPZzXq5BfTBLVwpLU9tm1gi0qjnfMCC9jJCIE4hjsJsbyjmIWgOMcOTfy9gHKFpcjW8n2BH9CHk7AzOnByif+pmwTiqjsnL+Wjh1uBjlGQ0soNIuH1wtMPzwEH1La3s8dwcxSFNqz5kQAhn+CwOq8ztvV4SHPpw=,iv:swangPYtm6B95Nl1hqhx+B6dn2XEU9bqE5W4BVf+58M=,tag:VYHMIynp+m9hyCYteusbXg==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLYzB5YUJxa2hFNm9PRlhV
            WmRnL2FHUUJGS0Q1aE9tRTdiUzRxbG5jWW1jCjRta3JNNUdvWVozUUM5T1hWNnMz
            Z0dPcjNKV3FNdktZNVVYdXFlOHFGK2MKLS0tIDd2YmRuRWRPQmZFY0pheURYZXZ5
            ekZQRHE1L2xFMERKQ0hjTWQxeGRyOGcKZiA1g3Vb4FhtUZZhPh3OcRCf7tVbPUE+
            neuYKjUbTR0NOcIEXyNPRL8Sh1gZBB0oMlCSFpDdo2Bxs+z8IXs/4Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qtewkeeguag6dt2ap94tjcp605v3mqfgqzea39snkhpp74jkheaq0nsga3
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-22T00:47:09Z"
    mac: ENC[AES256_GCM,data:5zZ2+LWkPxvrxucJjElQeU6uGp6t2aIyKHM3kKSyhGZGlvWzjeU5On0+YDF8b2Ba3W7M2hUVz+BXvV1gw/CW97BZs0mnpmRldkkyRd/+c+tF4l2BpM4D7sy3gVc+AQUmZwRztGxwzwA7Fl05cvFFsXzJsMhhRKmrPN8nn+srQOY=,iv:Us9vOSLiur73fN/65CRDVik4KLMSgMZDsh39W4U9suw=,tag:JyXlqlSHovQ75Dq5mJ8Wwg==,type:str]
    version: 3.13.3
