apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:DUm23nl/CY985ucD2JThKubxZ2j84wVKuaZI/y11W7sYTYwKMH5TCCbEHCqy/t9e8+pEQQtpNzPSlOZmZDeE+Am0k2ybHe4GY76qBUWjeog9XbhtI+Yocu/ZPxJu3yvJnPiQquBp2Aont+Ry3SdmSGcBmPSIZyEW3iUYtGVd+q0I5ZGDg5OblBVL2lX67hVq7vFCGvIln8MrI7J4Y1/VsANZTnmGQe5Cv0PZAS1C3ZFvLJP58Zu0RQe7IkFqEkDCsNOBJ40s0fGK4Omez7VTq8X6qSEkKq1K4pLBdpfjA3+EOYUD7v+viSLnD4A=,iv:wSE+Jh3D24rbX+m7Yj0NE3jY5H/lyt7Ar2bezcPqLeE=,tag:HdlGRdK5sWaMCtWvo5aG7g==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6MGZMMmtHQ0twM1lmMHlx
            Q0xzRFc2VEFyMi84ZHI5eDBZdnJvQVhnVWpBClNXYmZDT2FlR3ZWZ1pva3hSVTgz
            QzY4ODUvaG9EZVNQRTJFeWlzZXA2Y2sKLS0tIFFrOC90cG9FekZJTHF6bE9MNUxF
            eEtpNC9ZL1ZDSWdEeit2UEF4MXFYbk0K8BLmyWE21vW6EzxA+lCqncjrJhK6tiWt
            bMQpYKFYSG63/oVbtFaEctea9dQyBNd7c72YaxT6kGJZpHp65h9RdA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qtewkeeguag6dt2ap94tjcp605v3mqfgqzea39snkhpp74jkheaq0nsga3
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-20T14:34:37Z"
    mac: ENC[AES256_GCM,data:tktn9YWy+0Uq31yO7SKU+0gOWhEzKZmh1j7e2FGT4fCbE8PjhIY2gpkxqqIPlsI/65xa5uZJV0eHH3Mj8zTAXYonjS8A6ppyqmdrgsQnHDumYsTtkZwZW1YvOWxXY8P9ccpOyp/NBVZFo8iS0CLh+rQrOoYlwSJwqU94BjTBGII=,iv:cGPAdy+r8pcwL021XIPu3kEmRWpocHd0NjdSrMYn6+Y=,tag:dM7a/8vc1mLu2iT5qcXXZw==,type:str]
    version: 3.13.3
