apiVersion: v1
data:
    password: ENC[AES256_GCM,data:T5mhrMP7VAw=,iv:/yNc5HmNcUmfQxrFbbg/+IOEHKXMzZuJdl2MHmKGM2M=,tag:3vKFbKCZ5M70kqTe29HwEw==,type:str]
    user: ENC[AES256_GCM,data:Fd3rvh6YQuk=,iv:dA11mn1fhgHJnFvN6oAtnm6kg1ODKLebec0t4np148U=,tag:upwwa8TrgHTRUoyjizYr8A==,type:str]
kind: Secret
metadata:
    name: test-secret
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZNzVuN0NvcjJKRFMydTFD
            TjJtd204bWEzd3RNQVBQN2lTbWc5YkZMWmpjCnpRS2g1OGlqbDFjYXdjVzJmZ3NO
            SVIwNU9tZGxIZU5YWmwvTkcyNkkyRHcKLS0tIC9yZmZWODJ3Y1dWSXR3dElRSjlQ
            RlE0dGo4dk5nS1lLcS9mTnBYSkxhdHcKn3r6KsiHi/+kBJES0tDjC0O+ZYyjRJXb
            mvani3OlA24ASyoJSfpOq43LgLig4oIzNypIdGew4RXKKygDSKFg9Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qtewkeeguag6dt2ap94tjcp605v3mqfgqzea39snkhpp74jkheaq0nsga3
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-20T13:51:17Z"
    mac: ENC[AES256_GCM,data:LNwfe6yXZr0rHvbPH+nOfI4ytA2BNSNuyIZlIeiDt6EYPnhRHRSn0ZcJuFTCXnFFpdRHIQdK014Vtr8Yv+GFOE90CIWhCSDYvjmLzsFsnLd0gnV++lWi8xc86Jrb/iaNMugoF+F3hy6t9TBIOGT2gcDE48w5j/Vo63k/0+CsFjc=,iv:kP3mTzLXDNdyYDFa9p0cwaHBql2+G2r9NmpPjdxzTnU=,tag:rB/6cNe4SEx8U15QMOJFKA==,type:str]
    version: 3.13.3
